import type { Lesson } from '../../types/content'

export const m7LessonsA: Lesson[] = [
  // ── 7.1 ──────────────────────────────────────────────────────
  {
    id: 'm7l1',
    slug: 'static-and-dynamic',
    title: 'Static and dynamic web pages',
    summary:
      'Why a page that shows the same thing to everybody is not enough — and what PHP adds.',
    minutes: 12,
    outcomes: ['Defines dynamic web pages'],
    blocks: [
      {
        b: 'lead',
        text: 'Everything you have built so far is **static**: the file on the server is exactly what arrives in the browser. That is fine for a page about the school, and useless for a page that shows *your* marks.',
      },

      { b: 'h2', text: 'Static web pages' },
      {
        b: 'p',
        text: 'Static webpages display **fixed content**. They are built using HTML, and sometimes CSS and JavaScript. The content remains the same for every user and does not change unless the web developer manually updates the HTML code.',
      },

      { b: 'h2', text: 'Dynamic web pages' },
      {
        b: 'p',
        text: 'Dynamic webpages display content that **can change** based on user interactions, preferences or other factors. They are built with server-side languages such as **PHP, Ruby, Python or Node.js**, and often interact with databases to retrieve and store data.',
      },
      {
        b: 'p',
        text: 'A dynamic page is more interactive: a user requests something from the page, and obtains it as the result of their query.',
      },
      {
        b: 'table',
        head: ['Feature', 'Static webpages', 'Dynamic webpages'],
        firstColHead: true,
        rows: [
          ['Content', 'Fixed', 'Changes based on user interaction'],
          ['Technologies', 'HTML, CSS, JavaScript', 'HTML, CSS, PHP and a database such as MySQL'],
          ['Generation', 'Written once by hand', 'Generated by the server for each request'],
          ['Complexity', 'Simple', 'Higher — a server language and a database are involved'],
          ['Interactivity', 'Limited', 'High'],
          ['Performance', 'Fast — files are simply delivered', 'Slightly slower — processing happens first'],
          ['Maintenance', 'Edit the HTML by hand', 'Update through a backend interface, or automatically'],
        ],
      },
      {
        b: 'note',
        tone: 'exam',
        title: 'The one-sentence distinction',
        text: 'A **static** page is *stored* and sent. A **dynamic** page is *generated* and sent. Everything else in the table follows from that difference.',
      },

      { b: 'h2', text: 'What PHP is' },
      {
        b: 'p',
        text: '**PHP is a server-side scripting language widely used for web development.** Originally known as *Personal Home Page*, it was created by **Rasmus Lerdorf in 1994**.',
      },
      {
        b: 'p',
        text: 'It began as a set of Perl scripts to manage his own website and track visits. Recognising its potential beyond personal use, Lerdorf rewrote the tools in **C** and released **PHP/FI (Forms Interpreter) 1.0 in 1995**, providing basic tools for web form processing and database communication.',
      },
      {
        b: 'note',
        tone: 'history',
        title: 'The versions the notes list',
        text: '**3.0 (1998)** — a modular architecture and expanded database support. **4.0 (2000)** — the Zend Engine, with sessions and output buffering. **5.0 (2004)** — proper object-oriented programming: classes, interfaces, exceptions. **7.0 (2015)** — Zend Engine 3.0, major performance gains, scalar and return type declarations. **8.0 (2020)** — a JIT compiler, union types, named arguments and match expressions.',
      },
      {
        b: 'p',
        text: 'Rasmus Lerdorf himself put the history more modestly: *“I did not develop the PHP we know today. Dozens, if not hundreds of people developed PHP. I was simply the first developer.”*',
      },

      { b: 'h2', text: 'What PHP is used for' },
      {
        b: 'ul',
        items: [
          '**Content management systems** — WordPress and Drupal are written in PHP.',
          '**E-commerce** — Magento and WooCommerce, with product management and payment gateways.',
          '**Web frameworks** that streamline development with reusable components.',
          '**Social media platforms** — Facebook was built on PHP, and parts of it still are.',
          '**Forums** such as phpBB and vBulletin.',
          '**Web services and APIs** that process requests and deliver dynamic content.',
          '**Custom web applications** — CRMs, inventory systems, school management systems.',
        ],
      },

      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Your first dynamic page',
          code: `<?php
// This is a real PHP interpreter. Change anything and press Run.

$school = "Vidya College";
$year   = 2026;

echo "<h2>Welcome to $school</h2>";
echo "<p>The year is $year.</p>";
echo "<p>Next year will be " . ($year + 1) . ".</p>";
?>`,
          height: 240,
          note: 'A static page could show the year — but somebody would have to edit the file every January. PHP works it out each time the page is requested.',
        },
      },

      {
        b: 'quiz',
        questions: [
          {
            kind: 'mcq',
            q: 'Which best describes the difference between static and dynamic pages?',
            options: [
              'Static pages use HTML; dynamic pages use CSS',
              'A static page is stored and sent; a dynamic page is generated and sent',
              'Static pages cannot contain images',
              'Dynamic pages load faster',
            ],
            answer: 1,
            why: 'Storage versus generation. Dynamic pages are in fact slightly **slower**, because processing happens before anything is sent.',
          },
          {
            kind: 'mcq',
            q: 'Who created PHP, and in which year?',
            options: [
              'Tim Berners-Lee, 1989',
              'Rasmus Lerdorf, 1994',
              'Håkon Wium Lie, 1994',
              'The Zend team, 2000',
            ],
            answer: 1,
            why: 'Rasmus Lerdorf, in 1994. PHP/FI 1.0 followed in 1995, rewritten in C.',
          },
          {
            kind: 'fill',
            q: 'What did the abbreviation PHP originally stand for?',
            accept: ['personal home page'],
            why: 'Personal Home Page. Today it is a recursive abbreviation for *PHP: Hypertext Preprocessor*.',
            placeholder: 'three words',
          },
          {
            kind: 'multi',
            q: 'Which technologies are typically involved in a dynamic web page?',
            options: ['HTML', 'PHP', 'MySQL', 'A text editor only', 'CSS'],
            answers: [0, 1, 2, 4],
            why: 'HTML and CSS for the page, PHP to generate it, MySQL to store the data behind it.',
          },
        ],
      },

      {
        b: 'recap',
        items: [
          'Static: fixed content, stored and delivered, changed only by editing the file.',
          'Dynamic: content generated per request, often from a database.',
          'PHP is a server-side scripting language, created by Rasmus Lerdorf in 1994.',
          'PHP 3 modular · 4 Zend Engine · 5 OOP · 7 performance · 8 JIT.',
        ],
      },
    ],
  },

  // ── 7.2 ──────────────────────────────────────────────────────
  {
    id: 'm7l2',
    slug: 'how-php-works',
    title: 'How PHP works, and setting up a server',
    summary:
      'PHP runs on the server, before anything is sent. That single fact explains XAMPP, htdocs and localhost.',
    minutes: 15,
    outcomes: ['Defines dynamic web pages', 'Creates PHP code to save/retrieve data'],
    blocks: [
      {
        b: 'lead',
        text: 'HTML and CSS are executed on the **client’s** computer — the browser parses and renders them, using the client’s CPU and memory. PHP scripts are executed on the **server**, before any content is sent to the client. Nearly everything confusing about PHP follows from that one difference.',
      },

      { b: 'widget', spec: { widget: 'php-flow' } },

      { b: 'h2', text: 'The request, step by step' },
      {
        b: 'steps',
        items: [
          {
            title: 'A client requests a PHP page',
            text: 'The web server identifies the file as a PHP script **from its `.php` extension**.',
          },
          {
            title: 'The server hands the file to the PHP interpreter',
            text: 'The interpreter is installed on the server. It processes the PHP code inside the file.',
          },
          {
            title: 'PHP talks to the database if it needs to',
            text: 'If the script includes database operations, PHP communicates with the database — MySQL, for instance — to retrieve or manipulate data.',
          },
          {
            title: 'PHP generates dynamic content',
            text: 'Based on the script’s logic and any data retrieved, it produces output.',
          },
          {
            title: 'The output is converted into HTML',
            text: 'The interpreter turns the processed PHP into **HTML — the language browsers understand**.',
          },
          {
            title: 'The server responds, and the browser renders',
            text: 'The web server sends the generated HTML back to the client’s browser, which renders it. The visitor never sees a line of PHP.',
          },
        ],
      },
      {
        b: 'note',
        tone: 'exam',
        title: 'Client-side versus server-side load',
        text: 'HTML and CSS consume the **client’s** CPU, memory and power. PHP consumes the **server’s**. A question asking which resources are used, or which computer heats up, is testing exactly this.',
      },

      { b: 'h2', text: 'Why you need a server to test PHP' },
      {
        b: 'p',
        text: 'PHP runs on servers, so PHP scripts **cannot run directly on a local computer** the way HTML or JavaScript can. Double-click a `.php` file and the browser will show you the source code, or offer to download it — because nothing has interpreted it.',
      },
      {
        b: 'p',
        text: 'Instead of using a real remote server, developers temporarily turn their own computer into a **virtual server** for testing. This simulates a web server environment so pages can be viewed through a browser.',
      },

      { b: 'h2', text: 'The server packages' },
      {
        b: 'p',
        text: 'Setting up a virtual server usually means installing web server software such as **Apache** or Nginx, along with PHP and a database server such as MySQL. Four bundled packages make this easy by combining all the components into one installer.',
      },
      {
        b: 'table',
        head: ['Package', 'Stands for', 'Platform'],
        rows: [
          ['**WAMP**', 'Windows, Apache, MySQL, PHP', 'Windows'],
          ['**MAMP**', 'macOS, Apache, MySQL, PHP', 'macOS'],
          ['**LAMP**', 'Linux, Apache, MySQL, PHP', 'Linux — also the standard on real servers'],
          ['**XAMPP**', 'Cross-platform, Apache, MySQL, PHP, Perl', 'Windows, macOS and Linux'],
        ],
      },
      {
        b: 'p',
        text: 'They all bundle a **web server (Apache)**, a **database server (MySQL or MariaDB)** and **server-side scripting languages (PHP, Perl or Python)**, pre-configured so you do not have to set up each component individually.',
      },
      {
        b: 'note',
        tone: 'exam',
        title: 'The letters are the answer',
        text: 'WAMP, MAMP and LAMP differ **only in the first letter** — the operating system. XAMPP is the cross-platform one, and the extra P is Perl. Being asked to expand these is a standard question.',
      },

      { b: 'h2', text: 'Setting up XAMPP' },
      {
        b: 'steps',
        items: [
          { title: 'Download and install', text: 'Get the version for your operating system and run the installer. Choose the components you need — usually Apache, MySQL and PHP.' },
          { title: 'Start the services', text: 'Launch the XAMPP Control Panel and click **Start** next to Apache and MySQL.' },
          {
            title: 'Create a project folder',
            text: 'Navigate to the **htdocs** directory inside the XAMPP installation folder and create a new folder for your project, such as `my_project`.',
          },
          {
            title: 'Write a PHP file inside it',
            text: 'Create `index.php` and put some PHP in it.',
            code: `<?php\n  echo "Hello, world!";\n?>`,
            lang: 'php',
          },
          {
            title: 'Open it through the server',
            text: 'In your browser, type the localhost address — **not** the file path.',
            code: 'http://localhost/my_project/index.php',
            lang: 'text',
          },
        ],
      },
      {
        b: 'note',
        tone: 'warn',
        title: 'The mistake everybody makes once',
        text: 'Opening `C:\\xampp\\htdocs\\my_project\\index.php` by double-clicking shows the **source code**, because no server is involved. You must go through `http://localhost/…` so Apache hands the file to PHP first.',
      },
      {
        b: 'p',
        text: 'WAMP works the same way, with one difference in vocabulary: WAMP installs to `C:\\wamp64\\` (or `C:\\wamp\\` on 32-bit systems) and its document folder is called **`www`** rather than `htdocs`. So the path becomes `C:\\wamp64\\www\\myproject\\index.php`, reached at `http://localhost/myproject/index.php`. When WAMP is running correctly, its system-tray icon turns **green**.',
      },
      {
        b: 'note',
        tone: 'note',
        title: 'A .php file can hold HTML too',
        text: 'A file with a `.php` extension can contain HTML, CSS **and** PHP. The interpreter passes anything outside `<?php … ?>` through untouched. That is why the file extension, not the content, decides whether PHP runs.',
      },
      {
        b: 'note',
        tone: 'tip',
        title: 'On this platform',
        text: 'Nothing to install. A complete PHP 8 interpreter and a SQL engine are running inside this browser tab, so `http://localhost` and `htdocs` are things you need to know for the exam and for your own machine — but not in order to practise here.',
      },

      {
        b: 'quiz',
        questions: [
          {
            kind: 'mcq',
            q: 'What does a visitor see if they use View Source on a PHP page?',
            options: [
              'The PHP source code',
              'The generated HTML only',
              'Both the PHP and the HTML',
              'Nothing — View Source is disabled',
            ],
            answer: 1,
            why: 'PHP is consumed on the server. Only the HTML it generated crosses the network, so only HTML can be viewed.',
          },
          {
            kind: 'mcq',
            q: 'What does the P in XAMPP’s name stand for, that WAMP does not have?',
            options: ['PostgreSQL', 'Perl', 'Python', 'PHP'],
            answer: 1,
            why: 'XAMPP = Cross-platform, Apache, MySQL, PHP, **Perl**. All four packages already include PHP.',
          },
          {
            kind: 'mcq',
            q: 'A student saves `test.php` on the desktop and double-clicks it. The browser shows the PHP code as text. Why?',
            options: [
              'The file extension is wrong',
              'No server interpreted it — the file must be opened through http://localhost',
              'PHP does not work in that browser',
              'Apache is not installed on any computer',
            ],
            answer: 1,
            why: 'Without a server, nothing hands the file to the PHP interpreter. The file must sit in `htdocs` (or `www`) and be opened through localhost.',
          },
          {
            kind: 'order',
            q: 'Put the steps of serving a PHP page into order.',
            items: [
              'The client requests a .php page',
              'The web server passes the file to the PHP interpreter',
              'PHP runs the code, querying the database if needed',
              'PHP produces HTML output',
              'The server sends the HTML back to the browser',
              'The browser renders the page',
            ],
            why: 'Everything PHP does happens **before** anything reaches the browser.',
          },
          {
            kind: 'fill',
            q: 'In XAMPP, which folder must your project go into?',
            accept: ['htdocs', 'the htdocs folder', '/htdocs'],
            why: '`htdocs` in XAMPP; `www` in WAMP. Both are the document root Apache serves from.',
            placeholder: 'folder name',
          },
        ],
      },

      {
        b: 'recap',
        items: [
          'HTML and CSS run on the client; PHP runs on the server, before anything is sent.',
          'The `.php` extension is what makes the server call the interpreter.',
          'WAMP · MAMP · LAMP · XAMPP — Apache + MySQL + PHP, differing by platform.',
          'Project files go in `htdocs` (XAMPP) or `www` (WAMP), and are opened via `http://localhost/…`.',
        ],
      },
    ],
  },

  // ── 7.3 ──────────────────────────────────────────────────────
  {
    id: 'm7l3',
    slug: 'php-syntax',
    title: 'PHP syntax, echo and comments',
    summary:
      'Where PHP starts and stops, the two ways to print, and three comment styles.',
    minutes: 13,
    outcomes: ['Creates PHP code to save/retrieve data to and from MySQL'],
    blocks: [
      {
        b: 'lead',
        text: 'PHP code is written between `<?php` and `?>`. Everything outside those tags is passed through untouched — which is what makes it so easy to mix PHP into an HTML page.',
      },

      { b: 'h2', text: 'The tags' },
      {
        b: 'code',
        lang: 'php',
        code: `<?php
  // PHP code goes here
?>`,
      },
      {
        b: 'p',
        text: 'To trigger the PHP commands, the `<?php` tag is used. The entire block of PHP is placed after it and ended with a closing `?>` tag. Each statement written inside that pair is a **PHP command**.',
      },

      { b: 'h2', text: 'Embedding PHP in HTML' },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'PHP inside an HTML page',
          code: `<!DOCTYPE html>
<html>
<head>
  <title>Mixed</title>
</head>
<body>

  <h1>This heading is plain HTML</h1>

  <?php
    echo "<p>This paragraph was produced by PHP.</p>";
  ?>

  <p>And this is plain HTML again.</p>

</body>
</html>`,
          height: 300,
          note: 'Switch the output panel to **What PHP sent** and look carefully: the PHP tags are gone, and only HTML remains. That is what leaves the server.',
        },
      },

      { b: 'h2', text: 'The semicolon' },
      {
        b: 'p',
        text: 'In PHP, a semicolon notifies the computer that **one instruction has finished and a new one is about to begin**. Every statement needs one.',
      },
      {
        b: 'note',
        tone: 'warn',
        title: 'The most common beginner error',
        text: 'A missing semicolon produces `Parse error: syntax error, unexpected …` — and PHP reports it on the **following** line, because that is where it noticed. If the reported line looks fine, check the line above it.',
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Break it on purpose',
          code: `<?php
$name = "Nimali"
echo "Hello, $name!";
?>`,
          height: 190,
          note: 'The missing semicolon is on line 2, but the error names line 3. Add the semicolon and run it again. Getting used to reading these messages will save you hours.',
        },
      },

      { b: 'h2', text: 'echo and print' },
      {
        b: 'p',
        text: 'Both output data to the browser. They are almost the same, and the differences are examinable.',
      },
      {
        b: 'table',
        head: ['', '`echo`', '`print`'],
        firstColHead: true,
        rows: [
          ['Type', 'A language construct', 'A language construct'],
          ['Parameters', 'Can take **multiple** parameters, separated by commas', 'Can only take **one** argument'],
          ['Return value', 'No return value — always returns void', 'Returns **1**, so it can be used in expressions'],
          ['Performance', 'Slightly **faster**', 'Slightly slower, because of the return value'],
        ],
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'echo and print together',
          code: `<?php
  /* Area and perimeter of a rectangle */
  $length = 12;
  $width  = 5;

  $a = $length * $width;
  $p = 2 * ($length + $width);

  echo "Area is $a";
  echo "<br>";
  echo "Perimeter is $p";
  echo "<br>";

  print "Area is $a";
  print "<br>";
  print "Perimeter is $p";

  // echo can take several parameters at once:
  echo "<br>", "Length: ", $length, " Width: ", $width;
?>`,
          height: 330,
          note: 'Try `print "a", "b";` — it fails, because print takes only one argument. `echo "a", "b";` works.',
        },
      },
      {
        b: 'note',
        tone: 'note',
        title: 'PHP itself is not case sensitive',
        text: '`Echo`, `echo` and `eCHo` are all the same. **Variables are a different matter** — `$abc` and `$Abc` are two different variables. That asymmetry catches people out.',
      },

      { b: 'h2', text: 'Comments' },
      {
        b: 'p',
        text: 'PHP has three comment styles — more than HTML or CSS.',
      },
      {
        b: 'code',
        lang: 'php',
        code: `<?php
// Everything to the right of a double slash is a comment

# A hash does exactly the same thing

/*
   A multi-line comment,
   enclosed in slash-star.
*/

echo "Hello, World!";
?>`,
      },
      {
        b: 'note',
        tone: 'tip',
        title: 'A comment inside a line',
        text: 'Multi-line comments can sit **inside** an expression, which single-line comments cannot: `$x = 10 + /* 50 */ + 20;` gives 30, because the 50 is commented out.',
      },
      {
        b: 'p',
        text: 'Why comment at all? **Readability** — improve understanding. **Debugging** — isolate and identify issues by disabling a line. **Maintenance** — help whoever changes this next, including you in six months. **Collaboration** — communicate with a team. **Documentation** — record context and purpose.',
      },

      {
        b: 'challenge',
        spec: {
          id: 'm7c1',
          title: 'Print a formatted result',
          brief:
            'Using `echo`, output exactly: **The total is 250** followed by a line break, then **Average: 50**. Store 250 and 50 in variables first rather than typing them into the string.',
          lang: 'php',
          starter: `<?php

// Create the two variables, then echo the two lines.

?>`,
          hints: [
            'Assign with `$total = 250;` — the semicolon matters.',
            'A variable inside a double-quoted string is replaced by its value: `echo "The total is $total";`',
            'A line break in HTML output is `<br>`.',
          ],
          solution: `<?php
$total   = 250;
$average = 50;

echo "The total is $total";
echo "<br>";
echo "Average: $average";
?>`,
          checks: [
            { kind: 'output', contains: 'The total is 250', label: 'The first line reads "The total is 250"' },
            { kind: 'output', contains: 'Average: 50', label: 'The second line reads "Average: 50"' },
            { kind: 'source', pattern: '\\$[a-zA-Z_]\\w*\\s*=\\s*250', label: '250 is stored in a variable' },
            { kind: 'source', pattern: '\\$[a-zA-Z_]\\w*\\s*=\\s*50', label: '50 is stored in a variable' },
            { kind: 'source', pattern: 'echo', label: 'echo is used for the output' },
          ],
        },
      },

      {
        b: 'quiz',
        questions: [
          {
            kind: 'mcq',
            q: 'Which is a valid difference between `echo` and `print`?',
            options: [
              'print is faster than echo',
              'echo can take multiple parameters; print takes only one',
              'echo returns 1; print returns nothing',
              'print can only be used inside HTML',
            ],
            answer: 1,
            why: '`echo` accepts several comma-separated parameters and returns nothing. `print` takes one argument and returns 1.',
          },
          {
            kind: 'mcq',
            q: 'What does a semicolon do in PHP?',
            options: [
              'Ends a comment',
              'Marks the end of one instruction',
              'Separates a variable from its value',
              'Closes a PHP block',
            ],
            answer: 1,
            why: 'It tells the interpreter that one instruction has finished and another is about to begin.',
          },
          {
            kind: 'multi',
            q: 'Which of these begin a comment in PHP?',
            options: ['//', '#', '<!--', '/*', '--'],
            answers: [0, 1, 3],
            why: '`<!--` is HTML and `--` is SQL. PHP uses `//`, `#` and `/* … */`.',
          },
          {
            kind: 'mcq',
            q: 'What does this script output?',
            code: `<?php
$x = 10 + /* 50 */ + 20;
echo $x;
?>`,
            codeLang: 'php',
            options: ['80', '30', '10', 'A parse error'],
            answer: 1,
            why: 'The `/* 50 */` is a comment, so only 10 and 20 are added — giving **30**.',
          },
          {
            kind: 'tf',
            q: 'Writing `ECHO "hi";` causes an error, because PHP keywords are case sensitive.',
            answer: false,
            why: 'The PHP language itself is **not** case sensitive, so `ECHO` works. Variable names, however, *are* case sensitive.',
          },
        ],
      },

      {
        b: 'recap',
        items: [
          'PHP lives between `<?php` and `?>`; everything else passes through untouched.',
          'Every statement ends with a semicolon — and a missing one is reported on the next line.',
          '`echo` takes many parameters and returns nothing; `print` takes one and returns 1.',
          'Comments: `//`, `#`, and `/* … */`.',
          'The language is case-insensitive; variable names are not.',
        ],
      },
    ],
  },

  // ── 7.4 ──────────────────────────────────────────────────────
  {
    id: 'm7l4',
    slug: 'variables-and-data-types',
    title: 'Variables and data types',
    summary:
      'Everything starts with `$`. Six data types, and the debugging function that tells you which one you have.',
    minutes: 15,
    outcomes: ['Creates PHP code to save/retrieve data to and from MySQL'],
    blocks: [
      {
        b: 'lead',
        text: 'Variables store data that can be manipulated and retrieved later in a script. In PHP every one of them begins with a **dollar sign**.',
      },

      { b: 'h2', text: 'Declaring a variable' },
      {
        b: 'p',
        text: 'Variables in PHP should be declared using a **`$`**, informing the server that a variable is going to be created. PHP variables can hold values of any data type and **do not require explicit declaration of the type**.',
      },
      {
        b: 'code',
        lang: 'php',
        code: `<?php
$username = "Fred Smith";
echo $username;
echo "<br>";

// The value of one variable can be copied into another
$current_user = $username;
echo $current_user;

// Other types need no special syntax
$count = 17.5;
?>`,
      },

      { b: 'h2', text: 'Naming rules' },
      {
        b: 'ul',
        items: [
          'Must start with a **letter** or an **underscore `_`**.',
          '**Cannot start with a number.**',
          'Can only contain alphanumeric characters and underscores.',
          'Reserved words of the language cannot be used as variable names.',
          'Names are **case sensitive** — `$variable` and `$Variable` are different variables.',
        ],
      },
      {
        b: 'code',
        lang: 'php',
        code: `<?php
$abc   = "Welcome";        // valid
$Abc   = "w3resource.com"; // valid — and a DIFFERENT variable
$9xyz  = "Hello world";    // INVALID — starts with a number
$_xyz  = "Hello world";    // valid — starts with an underscore
$_9xyz = "Hello world";    // valid
?>`,
      },
      {
        b: 'note',
        tone: 'exam',
        title: 'The trick question',
        text: 'PHP **as a language** is not case sensitive, so `Echo` and `echo` are the same. **Variable names are case sensitive**, so `$abc` and `$Abc` are two different variables. Both halves of that sentence get examined.',
      },

      { b: 'h2', text: 'Variables inside strings' },
      {
        b: 'p',
        text: 'Strings must be enclosed in **single** or **double** quotation marks — and the choice matters.',
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Single quotes versus double',
          code: `<?php
$name = "Nimali";

echo "Hello, $name!";   // double quotes: the variable is replaced
echo "<br>";
echo 'Hello, $name!';   // single quotes: printed literally
echo "<br>";

// Joining with a full stop works in both
echo 'Hello, ' . $name . '!';
?>`,
          height: 230,
          note: 'Double quotes **interpolate** — they substitute the value of any variable inside them. Single quotes do not. This is the single most useful thing to know about PHP strings.',
        },
      },

      { b: 'h2', text: 'The six data types' },
      {
        b: 'dl',
        items: [
          { term: 'String', desc: 'A sequence of characters enclosed in single or double quotes: `$name = "John";`' },
          { term: 'Integer', desc: 'A whole number, positive or negative: `$number = 42;`' },
          { term: 'Float (Double)', desc: 'A number with a decimal point: `$pi = 3.14;`' },
          { term: 'Boolean', desc: 'Two possible states, `TRUE` or `FALSE`.' },
          { term: 'Array', desc: 'A collection of values, each accessed by an index or a key. Covered fully in lesson 9.' },
          { term: 'NULL', desc: 'The absence of a value — a variable that exists but holds nothing.' },
        ],
      },

      { b: 'h2', text: 'var_dump()' },
      {
        b: 'p',
        text: '`var_dump()` displays **structured information — the type and the value** — about one or more variables. Its detailed output makes it especially useful for debugging.',
      },
      {
        b: 'code',
        lang: 'php',
        code: `var_dump($variable1, $variable2, ...);`,
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'What type is it really?',
          code: `<?php
$number  = 42;
$string  = "Hello, World!";
$float   = 3.14;
$boolean = true;
$nothing = null;

var_dump($number, $string, $float, $boolean, $nothing);

echo "<hr>";

// Where var_dump earns its keep: these look the same when echoed
$a = 10;
$b = "10";
echo $a;  echo "<br>";
echo $b;  echo "<br>";
var_dump($a, $b);
?>`,
          height: 340,
          note: 'Echoing `$a` and `$b` gives an identical `10`. `var_dump` shows one is an `int` and the other a `string` — which is exactly the difference `===` cares about in the next lesson.',
        },
      },
      {
        b: 'note',
        tone: 'tip',
        title: 'var_dump is a debugging tool, not output',
        text: 'It is for you, while you are working. Take it out before anyone else sees the page — it exposes the internal shape of your data and looks like an error to a visitor.',
      },

      {
        b: 'challenge',
        spec: {
          id: 'm7c2',
          title: 'Calculate and report',
          brief:
            'Create variables for a student’s three marks — **78**, **65** and **82** — then calculate and print the **total** and the **average**. The output must contain the total and an average rounded to one decimal place or better.',
          lang: 'php',
          starter: `<?php

// Three marks, a total and an average.

?>`,
          hints: [
            'Add them with `$total = $m1 + $m2 + $m3;`.',
            'Divide by 3 for the average: `$average = $total / 3;`.',
            'Print with `echo "Total: $total";`.',
          ],
          solution: `<?php
$m1 = 78;
$m2 = 65;
$m3 = 82;

$total   = $m1 + $m2 + $m3;
$average = $total / 3;

echo "Total: $total";
echo "<br>";
echo "Average: " . round($average, 1);
?>`,
          checks: [
            { kind: 'output', contains: '225', label: 'The total (225) appears in the output' },
            { kind: 'output', pattern: '75(\\.0)?', label: 'The average (75) appears in the output' },
            { kind: 'source', pattern: '\\$\\w+\\s*=\\s*78', label: '78 is stored in a variable' },
            { kind: 'source', pattern: '\\+', label: 'The marks are added rather than typed in as a total' },
            { kind: 'source', pattern: '/\\s*3|/\\s*\\$', label: 'The average is calculated by division' },
          ],
        },
      },

      {
        b: 'quiz',
        questions: [
          {
            kind: 'mcq',
            q: 'Which of these is an invalid PHP variable name?',
            options: ['$_total', '$total9', '$9total', '$Total'],
            answer: 2,
            why: 'A variable name cannot **start** with a number. It may start with a letter or an underscore, and may contain numbers after that.',
          },
          {
            kind: 'mcq',
            q: 'What does this output?',
            code: `<?php
$name = "Kasun";
echo 'Hello $name';
?>`,
            codeLang: 'php',
            options: ['Hello Kasun', 'Hello $name', 'Hello', 'An error'],
            answer: 1,
            why: 'Single quotes do **not** interpolate variables, so `$name` is printed literally. Double quotes would give "Hello Kasun".',
          },
          {
            kind: 'mcq',
            q: 'What does `var_dump()` show that `echo` does not?',
            options: [
              'The variable name',
              'The data type as well as the value',
              'The memory address',
              'The line number',
            ],
            answer: 1,
            why: 'It prints structured information — type **and** value — which is why it is the standard debugging function.',
          },
          {
            kind: 'tf',
            q: '`$Marks` and `$marks` refer to the same variable.',
            answer: false,
            why: 'Variable names are case sensitive. These are two separate variables — a very common source of bugs.',
          },
          {
            kind: 'match',
            q: 'Match each value to its data type.',
            pairs: [
              { left: '42', right: 'Integer' },
              { left: '3.14', right: 'Float' },
              { left: '"Hello"', right: 'String' },
              { left: 'true', right: 'Boolean' },
            ],
            why: 'PHP works the type out from the value — you never declare it yourself.',
          },
        ],
      },

      {
        b: 'recap',
        items: [
          'Every variable starts with `$`; the type is inferred, never declared.',
          'Names start with a letter or underscore, never a number, and are case sensitive.',
          'Double quotes substitute variables; single quotes print them literally.',
          'Types: string, integer, float, boolean, array, NULL.',
          '`var_dump()` reveals type **and** value — for debugging only.',
        ],
      },
    ],
  },

  // ── 7.5 ──────────────────────────────────────────────────────
  {
    id: 'm7l5',
    slug: 'operators',
    title: 'Operators',
    summary:
      'Arithmetic, assignment, comparison, logical and increment — including the `==` versus `===` distinction.',
    minutes: 15,
    outcomes: ['Creates PHP code to save/retrieve data to and from MySQL'],
    blocks: [
      {
        b: 'lead',
        text: 'Operators are the verbs of a language. PHP has five families in the syllabus, and one of them contains the single most examined detail in the whole module: the difference between `==` and `===`.',
      },

      { b: 'h2', text: 'Arithmetic operators' },
      {
        b: 'table',
        head: ['Operator', 'Name', 'Example', 'Result'],
        compact: true,
        rows: [
          ['`+`', 'Addition', '`20 + 4`', '24'],
          ['`-`', 'Subtraction', '`20 - 4`', '16'],
          ['`*`', 'Multiplication', '`20 * 4`', '80'],
          ['`/`', 'Division', '`20 / 4`', '5'],
          ['`%`', 'Modulus — the remainder of a division', '`21 % 4`', '1'],
          ['`**`', 'Exponentiation — one number to the power of another', '`4 ** 2`', '16'],
        ],
      },
      {
        b: 'note',
        tone: 'note',
        title: 'No integer division operator',
        text: 'Python’s `//` is **not** an operator in PHP — there, two slashes begin a comment. `intdiv(20, 3)` is the function to use if you need whole-number division.',
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Every arithmetic operator',
          code: `<?php
echo 10 + 5;  echo "<br>";  # 15
echo 10 - 5;  echo "<br>";  # 5
echo 10 * 5;  echo "<br>";  # 50
echo 10 / 5;  echo "<br>";  # 2
echo 11 % 5;  echo "<br>";  # 1  ← remainder
echo 5 ** 2;  echo "<br>";  # 25 ← power
?>`,
          height: 250,
        },
      },

      { b: 'h2', text: 'Assignment operators' },
      {
        b: 'p',
        text: 'The basic assignment operator `=` assigns the value on the right to the variable on the left. **Augmented assignment** combines an operation with the assignment.',
      },
      {
        b: 'table',
        head: ['Operator', 'Written as', 'Equivalent to'],
        compact: true,
        rows: [
          ['`=`', '`$i = 10`', '`$i = 10`'],
          ['`+=`', '`$i += 10`', '`$i = $i + 10`'],
          ['`-=`', '`$i -= 5`', '`$i = $i - 5`'],
          ['`*=`', '`$i *= 3`', '`$i = $i * 3`'],
          ['`/=`', '`$i /= 5`', '`$i = $i / 5`'],
          ['`%=`', '`$i %= 5`', '`$i = $i % 5`'],
          ['`.=`', '`$i .= $j`', '`$i = $i . $j` — string concatenation'],
        ],
      },

      { b: 'h2', text: 'Comparison operators' },
      {
        b: 'table',
        head: ['Operator', 'Name', 'Asks'],
        compact: true,
        rows: [
          ['`==`', 'Equal', 'Are the two **values** equal?'],
          ['`===`', 'Identical', 'Are they equal **and of the same type**?'],
          ['`!=` or `<>`', 'Not equal', 'Are the values different?'],
          ['`!==`', 'Not identical', 'Are they different in value **or** in type?'],
          ['`<`', 'Less than', ''],
          ['`>`', 'Greater than', ''],
          ['`<=`', 'Less than or equal to', ''],
          ['`>=`', 'Greater than or equal to', ''],
        ],
      },
      {
        b: 'note',
        tone: 'exam',
        title: '== versus ===',
        text: '`10 == "10"` is **true** — the values match once PHP converts the string. `10 === "10"` is **false** — one is an integer, the other a string. Likewise `10 !== 10.0` is **true**, because an integer is not a float. Expect at least one question on this.',
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Comparisons, and what they really return',
          code: `<?php
// PHP prints true as 1 and false as nothing at all,
// so var_dump makes the results much easier to read.

var_dump(10 == 10);     // true
var_dump(10 == "10");   // true  — value matches
var_dump(10 === "10");  // FALSE — type differs
var_dump(10 != 5);      // true
var_dump(10 <> 5);      // true  — <> is the same as !=
var_dump(10 !== 10.0);  // TRUE  — int is not float
var_dump(10 < 5);       // false
var_dump(10 >= 11);     // false
?>`,
          height: 330,
          note: 'Notice `echo true` prints `1`, but `echo false` prints **nothing**. That surprises people who expect to see the word "false".',
        },
      },

      { b: 'h2', text: 'Logical operators' },
      {
        b: 'table',
        head: ['Operator', 'Name', 'Returns true when'],
        compact: true,
        rows: [
          ['`&&` or `and`', 'And', 'Both operands are true'],
          ['`||` or `or`', 'Or', 'At least one operand is true'],
          ['`!`', 'Not', 'Reverses the logical state of its operand'],
          ['`xor`', 'Exclusive or', 'Either operand is true, **but not both**'],
        ],
      },
      {
        b: 'note',
        tone: 'note',
        title: 'and / or have lower precedence',
        text: '`&&` and `and` mean the same thing but bind differently. `$x = true and false;` sets `$x` to **true**, because `=` binds tighter than `and`. Use `&&` and `||` and the problem disappears.',
      },

      { b: 'h2', text: 'Increment and decrement' },
      {
        b: 'p',
        text: 'These increase or decrease a variable’s value by one, and each has two forms.',
      },
      {
        b: 'compare',
        left: {
          title: 'Pre-increment `++$number`',
          items: [
            'The variable is incremented **first**',
            'Then the new value is used in the expression',
            '`$n = 5; echo ++$n;` outputs **6**',
          ],
        },
        right: {
          title: 'Post-increment `$number++`',
          items: [
            'The **current** value is used in the expression first',
            'Then the variable is incremented',
            '`$n = 5; echo $n++;` outputs **5**',
          ],
        },
      },
      {
        b: 'lab',
        spec: {
          lab: 'php',
          title: 'Pre versus post',
          code: `<?php
$number = 5;
echo ++$number;   // 6 — incremented first
echo "<br>";
echo $number;     // 6
echo "<hr>";

$number = 5;
echo $number++;   // 5 — used first, then incremented
echo "<br>";
echo $number;     // 6
echo "<hr>";

$number = 5;
echo --$number;   // 4
echo "<br>";
echo $number--;   // 4 — used first
echo "<br>";
echo $number;     // 3
?>`,
          height: 360,
          note: 'In both cases the variable ends up changed. The difference is only **what the expression evaluates to** at that moment — which matters enormously inside a loop.',
        },
      },

      {
        b: 'challenge',
        spec: {
          id: 'm7c3',
          title: 'Odd or even, without an if',
          brief:
            'Use the **modulus** operator to work out whether **17** is odd, and print the remainder when 17 is divided by 2. Then use `===` to show that `17` and `"17"` are **not** identical, printing the word **different** when they are not.',
          lang: 'php',
          starter: `<?php
$n = 17;

// 1. Print the remainder of $n divided by 2.

// 2. Compare $n with the string "17" using ===
//    and print "different" if they are not identical.

?>`,
          hints: [
            'The remainder operator is `%`, so `$n % 2` gives 1 for an odd number.',
            '`===` is false here because one value is an integer and the other a string.',
            'You can print conditionally with `if (...) { echo "different"; }`.',
          ],
          solution: `<?php
$n = 17;

echo "Remainder: " . ($n % 2);
echo "<br>";

if ($n !== "17") {
    echo "different";
}
?>`,
          checks: [
            { kind: 'source', pattern: '%', label: 'The modulus operator is used' },
            { kind: 'output', contains: '1', label: 'The remainder 1 is printed' },
            { kind: 'source', pattern: '===|!==', label: 'A strict comparison (=== or !==) is used' },
            { kind: 'output', contains: 'different', label: 'The word "different" is printed' },
          ],
        },
      },

      {
        b: 'quiz',
        questions: [
          {
            kind: 'mcq',
            q: 'What is printed?',
            code: `<?php
$n = 5;
echo $n++;
echo "-";
echo $n;
?>`,
            codeLang: 'php',
            options: ['5-5', '5-6', '6-6', '6-5'],
            answer: 1,
            why: 'Post-increment uses the current value (5) first, then increments. So the first echo prints 5 and the second prints 6.',
          },
          {
            kind: 'mcq',
            q: 'Which comparison returns **false**?',
            options: ['10 == "10"', '10 === 10', '10 === "10"', '10 != 5'],
            answer: 2,
            why: '`===` also compares **type**. An integer 10 and a string "10" have different types, so it is false.',
          },
          {
            kind: 'mcq',
            q: 'What is the value of `$i` at the end?',
            code: `<?php
$i = 20;
$i += 5;
$i /= 5;
$i **= 2;
echo $i;
?>`,
            codeLang: 'php',
            options: ['25', '5', '9', '100'],
            answer: 0,
            why: '20 + 5 = 25, then 25 / 5 = 5, then 5 to the power 2 = **25**.',
          },
          {
            kind: 'mcq',
            q: 'What does `21 % 4` evaluate to?',
            options: ['5', '5.25', '1', '4'],
            answer: 2,
            why: '`%` gives the **remainder**. 21 ÷ 4 is 5 remainder 1, so the answer is 1.',
          },
          {
            kind: 'multi',
            q: 'Which operators return true only when **both** operands are true?',
            options: ['&&', 'and', '||', 'xor', '!'],
            answers: [0, 1],
            why: '`&&` and `and` are both logical AND. `||` is OR, `xor` is exclusive OR, and `!` negates.',
          },
        ],
      },

      {
        b: 'recap',
        items: [
          'Arithmetic: `+ - * / %` and `**` for powers. No `//` — that is a comment.',
          'Augmented assignment: `+= -= *= /= %=` and `.=` for joining strings.',
          '`==` compares values; `===` compares value **and** type. Same for `!=` and `!==`.',
          'Logical: `&& and`, `|| or`, `!`, `xor`.',
          '`++$n` increments then uses; `$n++` uses then increments.',
        ],
      },
    ],
  },
]
